
name: 'jaffle_shop'
version: '0.1'
config-version: 2
profile: 'integration_tests'
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

vars:
  dbt_utils_dispatch_list: ['tsql_utils']

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view
        tags: ["staging", "hourly"]
seeds:
  +quote_columns: True